using System;
using UnityEngine;
using UnityMVC.Controller;
using UnityMVC.Events;
using UnityMVC.View;
using Object = System.Object;

namespace WTF.Player
{
    // Autogenerated code. DO NOT CHANGE unless it is really needed and you know what you are doing.
    public partial class WTFPlayerController : Controller
    {
        private WTFPlayerView View => _view;
        private WTFPlayerView _view;
        public  WTFPlayerControllerEvents Events => _events;
        private readonly WTFPlayerControllerEvents _events = new WTFPlayerControllerEvents();
        
        public override void SetView(View view)
        {
            if (_view != null)
            {
                if (_isDontDestroyOnLoad)
                {
                    UnityEngine.Object.Destroy(view.gameObject);
                    return;
                }
                
                Debug.LogException(new Exception($"More than one View are trying to access {this.GetType()}"));
                return;
            }
            _view = view as WTFPlayerView;
        }

        public override View GetView()
        {
            return _view;
        }

        public override bool IsActive()
        {
            bool viewExists = _view != null;
            bool isActive = viewExists && _view.gameObject.activeSelf;
            if (viewExists)
            {
                Debug.LogWarning($"View {typeof(WTFPlayerView).Name} does not exist");
            }
            if (!isActive)
            {
                Debug.LogWarning($"View {this.GetType().Name} not active");
            }
            return isActive && viewExists;
        }

        protected override void InternalAwake()
        {
            _events.onControllerInitialized?.Invoke(this);
        }
        protected override void InternalOnDestroy()
        {
            _events.onControllerDestroyed?.Invoke(this);
        }

        protected override void InternalOnEnable()
        {
            
        }

        protected override void InternalOnDisable()
        {
            
        }
    }
}